// <auto-generated />
using HRM_Plus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRM_Plus.Migrations
{
    [DbContext(typeof(HRM_PlusContext))]
    [Migration("20230324162800_Departamentos")]
    partial class Departamentos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HRM_Plus.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DescripcionPuesto")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombrePuesto")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UbicacionFisica")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("isActivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("HRM_Plus.Models.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DescripcionPuesto")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePuesto")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("SalarioMaximo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isActivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Puesto");
                });
#pragma warning restore 612, 618
        }
    }
}
